DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhZXhhZjJAZXhhbXBsZS5jb20iLCJleHAiOjE3MDk3OTU0ODcsInVzZXJJZCI6Mn0.QzHc-ErMsELfD4m9N0JT0kAmLim4FV-Kq_YjvmbcKG4